verbose: true
num_cells: 1 # Number of unit cells to generate

cell_domain:
  shape: rectangle
  bounds:
    x_min: 0
    x_max: 20
    y_min: 0
    y_max: 20
  init_method:
    name: random

inclusions:
  - init_method: random
  - periodicity: true # Whether the domain is periodic
  - min_surface_to_surface_distance: 0.5 # Minimum distance between shapes
  - shape: circle
    volume_fraction: 0.6
    size_params:
      radius:
        distribution:
          name: norm
          loc: 2
          scale: 0.5
  - shape: ellipse
    volume_fraction: 0.2
    size_params:
      semi_major_length:
        distribution:
          name: uniform
          loc: 4.0
          scale: 0.5
      semi_minor_length:
        distribution:
          name: uniform
          loc: 1.0
          scale: 1.0

optimiser:
  name: nmspg # Optimisation algorithm to use
  parameters:
    max_iterations: 1000 # Maximum number of iterations for the optimiser
