num_cells: 2 # Number of unit cells to generate

domain:
  shape: rectangle
  bounds: [0, 0, 30, 30] # x_min, y_min, x_max, y_max

shapes:
  - name: Circle
    vf: 0.3
    params:
      radius: uniform(1.5, 0.1)

  - name: Ellipse
    vf: 0.3
    params:
      semi_major_length: uniform(2, 0.1)
      semi_minor_length: uniform(1, 0.1)
      major_axis_angle: uniform(0, 360)

export:
  output_dir: ./scratch/outputs/test_12
  as_array: false
  format: png # png, jpg, pdf, json, pkl, yml, npz
  plot_with:
    shape_facecolor: None
    shape_edgecolor: red
    bg_facecolor: black
    bg_edgecolor: None
    size: [512, 512]
    dpi: 100

packing:
  periodic: false
  min_gap: 0.2

verbose: 1
rng_seed: 42
# # ----------------------------------------------

engine:
  init_method: uniform
  proj_buff_ratio: 2.0
  optimiser:
    name: nmspg
    max_iter: 1000
  adjust_bounds_to_exact_vf: false
