num_cells: 2 # Number of unit cells to generate

domain:
  shape: rectangle
  bounds: [0, 0, 30, 30] # x_min, y_min, x_max, y_max

shapes:
  - name: Circle
    vf: 0.7
    params:
      radius: uniform(1, 0.1)

image:
  domain:
    facecolor: black
    edgecolor: None
  shapes:
    facecolor: white
    edgecolor: None
  size: [512, 512]
  dpi: 100
  model: L

output_dir: /home/rajesh/work/repos/shapeforge/scratch/outputs

packing:
  periodic: false
  min_gap: 0.05

verbose: false
rng_seed: 42
# # ----------------------------------------------

engine:
  init_method: uniform
  proj_buff_ratio: 2.0
  optimiser:
    name: nmspg
    max_iter: 1000
  adjust_bounds_to_exact_vf: false
