# ============================================================================
# ShapeForge Configuration File
# Standard Unit System: Metric (e.g., mm for lengths) or Dimensionless
# ============================================================================

# ----------------------------------------------------------------------------
# Metadata & Execution
# ----------------------------------------------------------------------------
num_cells: 2
metadata:
  project_name: "shapeforge-demo"
  rng_seed: 42
  log_level: info

# ----------------------------------------------------------------------------
# Spatial Domain Definition
# ----------------------------------------------------------------------------
domain:
  shape: rectangle
  bounds:
    x_min: 0.0
    y_min: 0.0
    x_max: 10.0
    y_max: 10.0

# ----------------------------------------------------------------------------
# Inclusion Phase Geometry
# ----------------------------------------------------------------------------
shapes:
  - name: Circle
    volume_fraction: 0.6
    params:
      # params might be constant or might follow a distribution. Constant
      # values can be passed as float values, while the params with a
      # distribution must be defined with "distr_name(loc, scale)" signature
      radius: uniform(1, 0.1)

# ----------------------------------------------------------------------------
# Packing 
# ----------------------------------------------------------------------------
packing:
  periodic: false
  min_gap_ratio: 0.05
  proj_buffer_ratio: 2.0
  adjust_bounds_to_exact_vf: false

# ----------------------------------------------------------------------------
# Solver & Optimization Engine Configuration
# ----------------------------------------------------------------------------
solver:
  init_method: uniform # uniform | lhs | sobol
  optimiser:
    name: nmspg
    max_iter: 1000
    epsilon: 1.0e-6


# ----------------------------------------------------------------------------
# Export & Visualization Outputs
# ----------------------------------------------------------------------------
export:
  output_dir: ./scratch/outputs/test_1
  as_array: false
  formats: # png, jpg, pdf, json, pkl, yml, npz
    - png
    - json
  background: 0
  facecolor: 255
  image_dimensions: [512, 512]
  dpi: 100
